### ISSUE TITLE
[CHORE] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by m6z1** [BUS-TAM-E/BusTAME-Android#1]
## Description
> 프로젝트를 위한 초기 세팅 이슈

## Todo
- [x] git ignore 설정
- [x] package 구조 반영
- [x] color 추가
- [x] font 추가
- [x] base 설정
- [x] 권한 추가
- [x] 카카오맵 API 추가
